# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d51168f72510d1c45ad5ceaf9c5a1b7f765c41e750a8bd15939a35a99711a4c80d01288e32efb1e76537d3d7eaebe4a329d8cff99ead600c2671a67dceedd5da

test:
  secret_key_base: 3eb0f48614bcd3781dc7fd765a20286bbbffe063beab0033610b434f253aa6d4d59fe5adfc4fb39bd0d7b76e9ad81c56463c3a27b69e06cf403fb6a985ffbe5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
